# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profiling.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(234, 191)
        self.username = QtWidgets.QLineEdit(Form)
        self.username.setGeometry(QtCore.QRect(10, 20, 211, 31))
        self.username.setObjectName("username")
        self.redditChecked = QtWidgets.QCheckBox(Form)
        self.redditChecked.setGeometry(QtCore.QRect(10, 70, 211, 17))
        self.redditChecked.setObjectName("redditChecked")
        self.twitterChecked = QtWidgets.QCheckBox(Form)
        self.twitterChecked.setGeometry(QtCore.QRect(10, 90, 211, 17))
        self.twitterChecked.setObjectName("twitterChecked")
        self.profileButton = QtWidgets.QPushButton(Form)
        self.profileButton.setGeometry(QtCore.QRect(10, 120, 211, 31))
        self.profileButton.setObjectName("profileButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username.setText(_translate("Form", "Username"))
        self.redditChecked.setText(_translate("Form", "Download Reddit Users"))
        self.twitterChecked.setText(_translate("Form", "Download Twitter Users"))
        self.profileButton.setText(_translate("Form", "Generate Profile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
