# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stylo Application.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(469, 263)
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(20, 20, 61, 61))
        self.backButton.setObjectName("backButton")
        self.userOneTop = QtWidgets.QTextBrowser(Form)
        self.userOneTop.setGeometry(QtCore.QRect(90, 20, 361, 61))
        self.userOneTop.setObjectName("userOneTop")
        self.userTwoBottom = QtWidgets.QTextBrowser(Form)
        self.userTwoBottom.setGeometry(QtCore.QRect(90, 90, 361, 51))
        self.userTwoBottom.setObjectName("userTwoBottom")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(320, 150, 81, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 150, 41, 41))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(410, 150, 41, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 150, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.downloadReddit = QtWidgets.QPushButton(Form)
        self.downloadReddit.setGeometry(QtCore.QRect(90, 210, 75, 23))
        self.downloadReddit.setObjectName("downloadReddit")
        self.downloadTwitter = QtWidgets.QPushButton(Form)
        self.downloadTwitter.setGeometry(QtCore.QRect(90, 230, 75, 23))
        self.downloadTwitter.setObjectName("downloadTwitter")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(170, 210, 231, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 210, 41, 41))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.backButton.setText(_translate("Form", "<"))
        self.userOneTop.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("Form", "C-Value"))
        self.pushButton.setText(_translate("Form", "Reset"))
        self.pushButton_2.setText(_translate("Form", "Test"))
        self.downloadReddit.setText(_translate("Form", "Reddit"))
        self.downloadTwitter.setText(_translate("Form", "Twitter"))
        self.pushButton_3.setText(_translate("Form", "Go"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
