# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verification.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(361, 253)
        self.cUserOne = QtWidgets.QLineEdit(Form)
        self.cUserOne.setGeometry(QtCore.QRect(10, 20, 241, 31))
        self.cUserOne.setObjectName("cUserOne")
        self.cUserTwo = QtWidgets.QLineEdit(Form)
        self.cUserTwo.setGeometry(QtCore.QRect(10, 60, 241, 31))
        self.cUserTwo.setObjectName("cUserTwo")
        self.redditChecked = QtWidgets.QCheckBox(Form)
        self.redditChecked.setGeometry(QtCore.QRect(10, 100, 131, 16))
        self.redditChecked.setObjectName("redditChecked")
        self.twitterChecked = QtWidgets.QCheckBox(Form)
        self.twitterChecked.setGeometry(QtCore.QRect(10, 120, 141, 17))
        self.twitterChecked.setObjectName("twitterChecked")
        self.cValue = QtWidgets.QLineEdit(Form)
        self.cValue.setGeometry(QtCore.QRect(180, 100, 71, 31))
        self.cValue.setObjectName("cValue")
        self.resetC = QtWidgets.QPushButton(Form)
        self.resetC.setGeometry(QtCore.QRect(270, 100, 75, 31))
        self.resetC.setObjectName("resetC")
        self.testButton = QtWidgets.QPushButton(Form)
        self.testButton.setGeometry(QtCore.QRect(10, 150, 241, 31))
        self.testButton.setObjectName("testButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cUserOne.setText(_translate("Form", "Compare User One"))
        self.cUserTwo.setText(_translate("Form", "Compare User Two"))
        self.redditChecked.setText(_translate("Form", "Download Reddit Users"))
        self.twitterChecked.setText(_translate("Form", "Download Twitter Users"))
        self.resetC.setText(_translate("Form", "Reset C"))
        self.testButton.setText(_translate("Form", "Test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
